const {chromium}=require('playwright');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const shots=path.join(process.cwd(),'test-results');fs.mkdirSync(shots,{recursive:true});
(async()=>{
 const browser=await chromium.launch({headless:true});
 const page=await browser.newPage({viewport:{width:1440,height:1000}});
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto('http://localhost:3000');
 await page.getByRole('button',{name:/Explore with a demo account/}).click();
 await page.getByRole('heading',{name:/Hi, Alex/}).waitFor();
 const bounds=await page.locator('.phone').boundingBox();assert.equal(bounds.width,414);assert(Math.abs(bounds.x+bounds.width/2-720)<1);
 await page.screenshot({path:path.join(shots,'carebook-home.png')});
 await page.getByRole('button',{name:'Find a doctor'}).click();
 await page.getByRole('button',{name:/Dr. Sophia Chen/}).click();
 await page.getByRole('button',{name:'Book an appointment'}).click();
 await page.getByRole('button',{name:'09:00 AM',exact:true}).click();
 await page.getByRole('button',{name:'Confirm appointment',exact:true}).click();
 await page.getByRole('heading',{name:/A little time/}).waitFor();
 await page.getByRole('button',{name:'View appointment'}).click();
 await page.getByRole('button',{name:'Reschedule appointment'}).click();
 await page.getByRole('button',{name:'09:30 AM',exact:true}).click();
 await page.getByRole('button',{name:'Confirm new appointment'}).click();
 await page.getByRole('heading',{name:/A little time/}).waitFor();
 await page.getByRole('button',{name:'View appointment'}).click();
 page.once('dialog',d=>d.accept());
 await page.getByRole('button',{name:'Cancel appointment',exact:true}).click();
 await page.getByRole('button',{name:'Book another visit'}).waitFor();
 await page.getByRole('button',{name:'Go back'}).click();
 await page.getByRole('button',{name:'Profile',exact:true}).click();
 await page.getByRole('button',{name:/Personal information/}).click();
 await page.getByLabel('Phone number').fill('+1 555 123 4567');
 await page.getByRole('button',{name:'Save changes'}).click();
 await page.getByRole('button',{name:/Clinic workspace/}).click();
 await page.getByRole('heading',{name:/Your clinic/}).waitFor();
 await page.getByRole('button',{name:'Providers',exact:true}).click();
 await page.getByRole('spinbutton',{name:'Fee for Dr. Sophia Chen'}).fill('70');
 await page.getByRole('button',{name:'Save provider'}).first().click();
 await page.getByRole('button',{name:'Patients',exact:true}).click();
 await page.getByRole('heading',{name:'Alex Morgan',exact:true}).waitFor();
 await page.reload();await page.getByRole('heading',{name:/Hi, Alex/}).waitFor();
 await page.setViewportSize({width:390,height:844});
 await page.screenshot({path:path.join(shots,'carebook-mobile.png')});
 assert(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth));
 assert.deepEqual(errors,[]);
 await browser.close();
 console.log('PASS: centered mobile shell, booking, rescheduling, cancellation, profile edit, admin, reload persistence, mobile overflow, browser errors');
})().catch(e=>{console.error(e);process.exit(1)});
