export type Doctor = {id:string;name:string;specialty:string;initials:string;color:string;experience:number;rating:string;fee:number;about:string;kind:'doctor'|'service';duration:number;active:boolean};
export type Patient = {id:string;name:string;email:string;phone:string;dob:string;gender:string;blood:string;allergies:string};
export type Booking = {id:string;patientId:string;doctorId:string;date:string;time:string;status:'Confirmed'|'Completed'|'Cancelled';payment:'Pay at clinic'|'Demo card';notes:string;createdAt:string};
export type Notice = {id:string;patientId:string;text:string;read:boolean;createdAt:string};
export type State = {doctors:Doctor[];patients:Patient[];bookings:Booking[];notices:Notice[]};
export const times=['09:00 AM','09:30 AM','10:00 AM','10:30 AM','11:00 AM','11:30 AM','02:00 PM','02:30 PM','03:00 PM','03:30 PM'];
export function dateKey(offset=0){const parts=new Intl.DateTimeFormat('en-US',{timeZone:'America/New_York',year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(new Date());const get=(type:string)=>Number(parts.find(p=>p.type===type)?.value);return new Date(Date.UTC(get('year'),get('month')-1,get('day')+offset)).toISOString().slice(0,10)}
export const patient:Patient={id:'patient-demo',name:'Alex Morgan',email:'alex@example.com',phone:'+1 212 555 0142',dob:'1994-05-18',gender:'Male',blood:'O+',allergies:'None'};
export const doctors:Doctor[]=[
{id:'d1',name:'Dr. Sophia Chen',specialty:'General physician',initials:'SC',color:'#e0eceb',experience:12,rating:'4.9',fee:65,duration:30,kind:'doctor',active:true,about:'A thoughtful approach to everyday care. Dr. Chen helps with annual checkups, preventive health, and common illnesses, with time to listen to every concern.'},
{id:'d2',name:'Dr. James Wilson',specialty:'Cardiologist',initials:'JW',color:'#e6e4f1',experience:16,rating:'4.9',fee:110,duration:30,kind:'doctor',active:true,about:'Specialist in heart health, preventive cardiology, and blood pressure management. A clear, personal care plan for every patient.'},
{id:'d3',name:'Dr. Maya Patel',specialty:'Dermatologist',initials:'MP',color:'#f4e5dc',experience:9,rating:'4.8',fee:85,duration:30,kind:'doctor',active:true,about:'Expert care for skin, hair, and nails. Consultations include acne, eczema, and personalized skin health guidance.'},
{id:'d4',name:'Dr. Oliver Reed',specialty:'Dentist',initials:'OR',color:'#e2eaf3',experience:11,rating:'4.8',fee:75,duration:30,kind:'doctor',active:true,about:'Gentle dental care, routine examinations, and preventive treatments in a comfortable environment.'},
{id:'s1',name:'Complete health check',specialty:'Health screening',initials:'HC',color:'#e5eddd',experience:0,rating:'4.9',fee:149,duration:30,kind:'service',active:true,about:'A clinic visit including a general examination, blood pressure check, and sample collection for a basic blood panel. Demo package; results are not generated.'},
{id:'s2',name:'Blood test package',specialty:'Lab services',initials:'BT',color:'#f2e3ea',experience:0,rating:'4.8',fee:49,duration:30,kind:'service',active:true,about:'Sample collection for a complete blood count at our clinic. The clinic team will explain preparation requirements before your visit.'}];
export function seed():State{return {doctors:structuredClone(doctors),patients:[patient],bookings:[{id:'CB-1001',patientId:patient.id,doctorId:'d1',date:dateKey(2),time:'10:00 AM',status:'Confirmed',payment:'Pay at clinic',notes:'Annual checkup',createdAt:new Date().toISOString()},{id:'CB-1000',patientId:patient.id,doctorId:'d3',date:dateKey(-12),time:'02:00 PM',status:'Completed',payment:'Demo card',notes:'Skin consultation',createdAt:new Date().toISOString()}],notices:[{id:'n1',patientId:patient.id,text:'Welcome to Carebook. Your next step toward feeling better starts here.',read:false,createdAt:new Date().toISOString()}]}}
