import { transaction } from '@/lib/store';
import { times, dateKey, seed, Patient } from '@/lib/data';
import { randomUUID } from 'node:crypto';
export const runtime='nodejs';
export const dynamic='force-dynamic';
export async function GET(){return Response.json(await transaction(s=>s))}
export async function POST(request:Request){try{const b=await request.json();const result=await transaction(s=>{
if(b.action==='reset'){Object.assign(s,seed());return s}
if(b.action==='login'){const p=s.patients.find(p=>p.email.toLowerCase()===String(b.email).toLowerCase());if(!p)throw Error('No demo account found. Please register.');return p}
if(b.action==='register'){if(!b.name?.trim()||!/^\S+@\S+\.\S+$/.test(b.email))throw Error('Enter a name and valid email.');if(s.patients.some(p=>p.email.toLowerCase()===b.email.toLowerCase()))throw Error('An account with this email already exists.');const p:Patient={id:randomUUID(),name:b.name.trim(),email:b.email.toLowerCase(),phone:b.phone||'',dob:'',gender:'Prefer not to say',blood:'Unknown',allergies:'None'};s.patients.push(p);return p}
if(b.action==='profile'){const p=s.patients.find(p=>p.id===b.patientId);if(!p)throw Error('Patient not found.');if(!b.name?.trim())throw Error('Name is required.');for(const k of ['name','phone','dob','gender','blood','allergies'] as const){if(typeof b[k]==='string')p[k]=b[k]}return p}
if(b.action==='book'){const d=s.doctors.find(d=>d.id===b.doctorId&&d.active);if(!d||!s.patients.some(p=>p.id===b.patientId))throw Error('Select an available provider and patient.');if(!/^\d{4}-\d{2}-\d{2}$/.test(b.date)||b.date<dateKey(1)||b.date>dateKey(14)||!times.includes(b.time))throw Error('Select a valid future date and time.');if(!['Pay at clinic','Demo card'].includes(b.payment))throw Error('Choose a payment option.');if(s.bookings.some(a=>a.doctorId===b.doctorId&&a.date===b.date&&a.time===b.time&&a.status==='Confirmed'&&a.id!==b.rescheduleId))throw Error('This slot was just booked. Please choose another.');if(b.rescheduleId){const old=s.bookings.find(a=>a.id===b.rescheduleId&&a.patientId===b.patientId&&a.status==='Confirmed');if(!old)throw Error('Appointment cannot be rescheduled.');old.status='Cancelled'}const a={id:'CB-'+randomUUID().slice(0,8).toUpperCase(),patientId:b.patientId,doctorId:b.doctorId,date:b.date,time:b.time,status:'Confirmed' as const,payment:b.payment,notes:String(b.notes||'').slice(0,500),createdAt:new Date().toISOString()};s.bookings.unshift(a);s.notices.unshift({id:randomUUID(),patientId:b.patientId,text:`${b.rescheduleId?'Rescheduled':'Confirmed'}: ${d.name} on ${b.date} at ${b.time}. Booking ${a.id}.`,read:false,createdAt:new Date().toISOString()});return a}
if(b.action==='status'){const a=s.bookings.find(a=>a.id===b.id);if(!a)throw Error('Booking not found.');if(!['Cancelled','Completed','Confirmed'].includes(b.status))throw Error('Invalid status.');if(b.status==='Confirmed'&&s.bookings.some(x=>x.id!==a.id&&x.doctorId===a.doctorId&&x.date===a.date&&x.time===a.time&&x.status==='Confirmed'))throw Error('That slot is occupied.');a.status=b.status;s.notices.unshift({id:randomUUID(),patientId:a.patientId,text:`Appointment ${a.id} is now ${b.status.toLowerCase()}.`,read:false,createdAt:new Date().toISOString()});return a}
if(b.action==='read'){s.notices.filter(n=>n.patientId===b.patientId).forEach(n=>n.read=true);return {ok:true}}
if(b.action==='provider'){const d=s.doctors.find(d=>d.id===b.id);if(!d)throw Error('Provider not found.');if(!Number.isFinite(Number(b.fee))||Number(b.fee)<0)throw Error('Enter a valid fee.');d.active=Boolean(b.active);d.fee=Number(b.fee);return d}
throw Error('Unknown action.');});return Response.json(result)}catch(e){return Response.json({error:e instanceof Error?e.message:'Request failed'},{status:400})}}
